
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef _sdbuscpp_src_proxy_org_bluez_Battery1_battery1_proxy_h_proxy_H_
#define _sdbuscpp_src_proxy_org_bluez_Battery1_battery1_proxy_h_proxy_H_

#include <sdbus-c++/sdbus-c++.h>
#include <string>

namespace org::bluez {

class Battery1_proxy {
 public:
  static constexpr auto INTERFACE_NAME = "org.bluez.Battery1";

  Battery1_proxy(const Battery1_proxy&) = delete;
  Battery1_proxy& operator=(const Battery1_proxy&) = delete;
  Battery1_proxy(Battery1_proxy&&) = delete;
  Battery1_proxy& operator=(Battery1_proxy&&) = delete;

 protected:
  explicit Battery1_proxy(sdbus::IProxy& proxy) : m_proxy(proxy) {}

  ~Battery1_proxy() = default;

  void registerProxy() {}

 public:
  uint8_t Percentage() {
    return m_proxy.getProperty("Percentage")
        .onInterface(INTERFACE_NAME)
        .get<uint8_t>();
  }

 private:
  sdbus::IProxy& m_proxy;
};

}  // namespace org::bluez

#endif
