
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef _sdbuscpp_src_proxy_org_bluez_GattCharacteristic1_gatt_characteristic1_proxy_h_proxy_H_
#define _sdbuscpp_src_proxy_org_bluez_GattCharacteristic1_gatt_characteristic1_proxy_h_proxy_H_

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org::bluez {

class GattCharacteristic1_proxy {
 public:
  static constexpr auto INTERFACE_NAME = "org.bluez.GattCharacteristic1";

  GattCharacteristic1_proxy(const GattCharacteristic1_proxy&) = delete;
  GattCharacteristic1_proxy& operator=(const GattCharacteristic1_proxy&) =
      delete;
  GattCharacteristic1_proxy(GattCharacteristic1_proxy&&) = delete;
  GattCharacteristic1_proxy& operator=(GattCharacteristic1_proxy&&) = delete;

 protected:
  explicit GattCharacteristic1_proxy(sdbus::IProxy& proxy) : m_proxy(proxy) {}

  ~GattCharacteristic1_proxy() = default;

  void registerProxy() {}

 public:
  std::vector<uint8_t> ReadValue(
      const std::map<std::string, sdbus::Variant>& options) {
    std::vector<uint8_t> result;
    m_proxy.callMethod("ReadValue")
        .onInterface(INTERFACE_NAME)
        .withArguments(options)
        .storeResultsTo(result);
    return result;
  }

  void WriteValue(const std::vector<uint8_t>& value,
                  const std::map<std::string, sdbus::Variant>& options) {
    m_proxy.callMethod("WriteValue")
        .onInterface(INTERFACE_NAME)
        .withArguments(value, options);
  }

  std::tuple<sdbus::UnixFd, uint16_t> AcquireWrite(
      const std::map<std::string, sdbus::Variant>& options) {
    std::tuple<sdbus::UnixFd, uint16_t> result;
    m_proxy.callMethod("AcquireWrite")
        .onInterface(INTERFACE_NAME)
        .withArguments(options)
        .storeResultsTo(result);
    return result;
  }

  std::tuple<sdbus::UnixFd, uint16_t> AcquireNotify(
      const std::map<std::string, sdbus::Variant>& options) {
    std::tuple<sdbus::UnixFd, uint16_t> result;
    m_proxy.callMethod("AcquireNotify")
        .onInterface(INTERFACE_NAME)
        .withArguments(options)
        .storeResultsTo(result);
    return result;
  }

  void StartNotify() {
    m_proxy.callMethod("StartNotify").onInterface(INTERFACE_NAME);
  }

  void StopNotify() {
    m_proxy.callMethod("StopNotify").onInterface(INTERFACE_NAME);
  }

 public:
  std::string UUID() {
    return m_proxy.getProperty("UUID")
        .onInterface(INTERFACE_NAME)
        .get<std::string>();
  }

  sdbus::ObjectPath Service() {
    return m_proxy.getProperty("Service")
        .onInterface(INTERFACE_NAME)
        .get<sdbus::ObjectPath>();
  }

  std::vector<uint8_t> Value() {
    return m_proxy.getProperty("Value")
        .onInterface(INTERFACE_NAME)
        .get<std::vector<uint8_t>>();
  }

  bool Notifying() {
    return m_proxy.getProperty("Notifying")
        .onInterface(INTERFACE_NAME)
        .get<bool>();
  }

  std::vector<std::string> Flags() {
    return m_proxy.getProperty("Flags")
        .onInterface(INTERFACE_NAME)
        .get<std::vector<std::string>>();
  }

  bool WriteAcquired() {
    return m_proxy.getProperty("WriteAcquired")
        .onInterface(INTERFACE_NAME)
        .get<bool>();
  }

  bool NotifyAcquired() {
    return m_proxy.getProperty("NotifyAcquired")
        .onInterface(INTERFACE_NAME)
        .get<bool>();
  }

 private:
  sdbus::IProxy& m_proxy;
};

}  // namespace org::bluez

#endif
