
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef _sdbuscpp_src_proxy_org_bluez_GattManager1_gatt_manager1_proxy_h_proxy_H_
#define _sdbuscpp_src_proxy_org_bluez_GattManager1_gatt_manager1_proxy_h_proxy_H_

#include <sdbus-c++/sdbus-c++.h>
#include <string>

namespace org::bluez {

class GattManager1_proxy {
 public:
  static constexpr auto INTERFACE_NAME = "org.bluez.GattManager1";

  GattManager1_proxy(const GattManager1_proxy&) = delete;
  GattManager1_proxy& operator=(const GattManager1_proxy&) = delete;
  GattManager1_proxy(GattManager1_proxy&&) = delete;
  GattManager1_proxy& operator=(GattManager1_proxy&&) = delete;

 protected:
  explicit GattManager1_proxy(sdbus::IProxy& proxy) : m_proxy(proxy) {}

  ~GattManager1_proxy() = default;

  void registerProxy() {}

 public:
  void RegisterApplication(
      const sdbus::ObjectPath& application,
      const std::map<std::string, sdbus::Variant>& options) {
    m_proxy.callMethod("RegisterApplication")
        .onInterface(INTERFACE_NAME)
        .withArguments(application, options);
  }

  void UnregisterApplication(const sdbus::ObjectPath& application) {
    m_proxy.callMethod("UnregisterApplication")
        .onInterface(INTERFACE_NAME)
        .withArguments(application);
  }

 private:
  sdbus::IProxy& m_proxy;
};

}  // namespace org::bluez

#endif
