
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef _sdbuscpp_src_proxy_org_bluez_NetworkServer1_network_server1_proxy_h_proxy_H_
#define _sdbuscpp_src_proxy_org_bluez_NetworkServer1_network_server1_proxy_h_proxy_H_

#include <sdbus-c++/sdbus-c++.h>
#include <string>

namespace org::bluez {

class NetworkServer1_proxy {
 public:
  static constexpr auto INTERFACE_NAME = "org.bluez.NetworkServer1";

  NetworkServer1_proxy(const NetworkServer1_proxy&) = delete;
  NetworkServer1_proxy& operator=(const NetworkServer1_proxy&) = delete;
  NetworkServer1_proxy(NetworkServer1_proxy&&) = delete;
  NetworkServer1_proxy& operator=(NetworkServer1_proxy&&) = delete;

 protected:
  explicit NetworkServer1_proxy(sdbus::IProxy& proxy) : m_proxy(proxy) {}

  ~NetworkServer1_proxy() = default;

  void registerProxy() {}

 public:
  void Register(const std::string& uuid, const std::string& bridge) {
    m_proxy.callMethod("Register")
        .onInterface(INTERFACE_NAME)
        .withArguments(uuid, bridge);
  }

  void Unregister(const std::string& uuid) {
    m_proxy.callMethod("Unregister")
        .onInterface(INTERFACE_NAME)
        .withArguments(uuid);
  }

 private:
  sdbus::IProxy& m_proxy;
};

}  // namespace org::bluez

#endif
