
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef _sdbuscpp_src_proxy_org_bluez_AgentManager_agent_manager1_proxy_h_proxy_H_
#define _sdbuscpp_src_proxy_org_bluez_AgentManager_agent_manager1_proxy_h_proxy_H_

#include <sdbus-c++/sdbus-c++.h>
#include <string>

namespace org::bluez {

class AgentManager1_proxy {
 public:
  static constexpr auto INTERFACE_NAME = "org.bluez.AgentManager1";

  AgentManager1_proxy(const AgentManager1_proxy&) = delete;
  AgentManager1_proxy& operator=(const AgentManager1_proxy&) = delete;
  AgentManager1_proxy(AgentManager1_proxy&&) = delete;
  AgentManager1_proxy& operator=(AgentManager1_proxy&&) = delete;

 protected:
  explicit AgentManager1_proxy(sdbus::IProxy& proxy) : m_proxy(proxy) {}

  ~AgentManager1_proxy() = default;

  void registerProxy() {}

 public:
  void RegisterAgent(const sdbus::ObjectPath& agent,
                     const std::string& capability) {
    m_proxy.callMethod("RegisterAgent")
        .onInterface(INTERFACE_NAME)
        .withArguments(agent, capability);
  }

  void UnregisterAgent(const sdbus::ObjectPath& agent) {
    m_proxy.callMethod("UnregisterAgent")
        .onInterface(INTERFACE_NAME)
        .withArguments(agent);
  }

  void RequestDefaultAgent(const sdbus::ObjectPath& agent) {
    m_proxy.callMethod("RequestDefaultAgent")
        .onInterface(INTERFACE_NAME)
        .withArguments(agent);
  }

 private:
  sdbus::IProxy& m_proxy;
};

}  // namespace org::bluez

#endif
