
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef _sdbuscpp_src_proxy_org_bluez_BatteryProviderManager1_battery_provider_manager1_proxy_h_proxy_H_
#define _sdbuscpp_src_proxy_org_bluez_BatteryProviderManager1_battery_provider_manager1_proxy_h_proxy_H_

#include <sdbus-c++/sdbus-c++.h>

namespace org::bluez {

class BatteryProviderManager1_proxy {
 public:
  static constexpr auto INTERFACE_NAME = "org.bluez.BatteryProviderManager1";

  BatteryProviderManager1_proxy(const BatteryProviderManager1_proxy&) = delete;
  BatteryProviderManager1_proxy& operator=(
      const BatteryProviderManager1_proxy&) = delete;
  BatteryProviderManager1_proxy(BatteryProviderManager1_proxy&&) = delete;
  BatteryProviderManager1_proxy& operator=(BatteryProviderManager1_proxy&&) =
      delete;

 protected:
  explicit BatteryProviderManager1_proxy(sdbus::IProxy& proxy)
      : m_proxy(proxy) {}

  ~BatteryProviderManager1_proxy() = default;

  void registerProxy() {}

 public:
  void RegisterBatteryProvider(const sdbus::ObjectPath& provider) {
    m_proxy.callMethod("RegisterBatteryProvider")
        .onInterface(INTERFACE_NAME)
        .withArguments(provider);
  }

  void UnregisterBatteryProvider(const sdbus::ObjectPath& provider) {
    m_proxy.callMethod("UnregisterBatteryProvider")
        .onInterface(INTERFACE_NAME)
        .withArguments(provider);
  }

 private:
  sdbus::IProxy& m_proxy;
};

}  // namespace org::bluez

#endif
